### ISSUE TITLE
How to create iam_uncased.scorer

### ISSUE THREAD

**Issue by eaedk** [dredwardhyde/iam-crnn-ctc-recognition#1]
Please, I want to know how you create the .scorer file.

**Comment by dredwardhyde** [comment]
https://deepspeech.readthedocs.io/en/v0.9.3/Scorer.html

**Comment by eaedk** [comment]
can I use your score with another chars, chars_dict ??

**Comment by eaedk** [comment]
here is my chars... 
```Python3
chars = sorted(list(set(list("""_ 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&\'()*+,-./:;<=>?@[]^`{|}~"""))))
```

The model don't converge is it due to the scorer, now I use your `iam_uncased.scorer` ? if yes, please help me to create another scorer.

**Comment by eaedk** [comment]
is somebody here ?

**Comment by james-ralph8555** [comment]
The included iam_uncased.scorer only contains words from the iam dataset, and will not work well with other words.  Consider using deepspeech's scorer, based on the LibreSpeech clean corpus: https://github.com/mozilla/DeepSpeech/releases/tag/v0.9.3
